[[pages]]
path = "home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/simple.py"
name = "Page 2 - Simpliest try"
icon = "2ï¸âƒ£"



[[pages]]
path = "pages/prompt_template.py"
name = "Page 3 - Second simpliest try"
icon = "3ï¸âƒ£"


[[pages]]
path = "pages/home_exercise.py"
name = "Page 4 - More complex try"
icon = "4ï¸âƒ£"

